language: node_js
node_js:
  - 0.6
before_script:
  - "export DISPLAY=:99.0" 
  - "sh -e /etc/init.d/xvfb start"
  - npm install connect
  - node test/js/server.js ../ &
  - sleep 5
script: phantomjs test/qunit/run-qunit.js "http://localhost:1337/index.html"